### ISSUE TITLE
Use same default width as Racket Style Guide

### ISSUE THREAD

**Issue by jackfirth** [sorawee/fmt#6]
The default for `raco fmt --width` is 80, but the [Racket Style Guide](https://docs.racket-lang.org/style/Textual_Matters.html#%28part._.Line_.Width%29) prescribes 102 as a column limit. I think these should be consistent.

**Comment by sorawee** [comment]
Personally I don't agree with this column limit. It makes diffing in GitHub looks bad. But for consistency, it makes sense to follow the style guide.
