### ISSUE TITLE
`for/set` loops with multiple body forms get forced onto one line

### ISSUE THREAD

**Issue by jackfirth** [sorawee/fmt#64]
`fmt` changes this code:

```scheme
(for/set ([x (in-range 0 10)])
  (displayln x)
  (* x x))
```

into this:

```scheme
(for/set ([x (in-range 0 10)]) (displayln x) (* x x))
```

However, it only does this for `for/set` for loops. Other for loops don't get their body forms squashed onto the same line. `for/set` should have the same behavior as the other loops.

**Comment by sorawee** [comment]
This should be very easy. May I suggest that you try fixing it? :-)

But if by tonight you have not done it yet, I will do it myself.

**Comment by jackfirth** [comment]
Will do, after work :) I had a hunch this one would be easy.
