### ISSUE TITLE
Submit to code formatting "aggregators"?

### ISSUE THREAD

**Issue by greghendershott** [sorawee/fmt#7]
From https://github.com/greghendershott/racket-mode/issues/561:

When you think it's stable enough, and if you want to get into "no good deed goes unpunished" territory :smile::

You might want to submit this to one or more packages that aggregate code formatters for various langs.

For example there's the Emacs package [format-all-the-code](https://github.com/lassik/emacs-format-all-the-code).

Although there seem to be other things like `unibeautify` and `prettier`, those two examples are node packages --- I'm not sure your good deed warrants cruel and unusual punishment. :wink:

**Comment by sorawee** [comment]
I was not seeking for punishment. Punishment was seeking for me.

Joking aside, thanks to @lassik for adding `fmt` to `format-all-the-code` in https://github.com/lassik/emacs-format-all-the-code/commit/63a79f9721b6c5b7337ccebbc652803c78aaa157. And with that, I will close this issue.
