### ISSUE TITLE
Class expressions aren't formatted well

### ISSUE THREAD

**Issue by jackfirth** [sorawee/fmt#73]
`fmt` turns this code:

```scheme
(class* foo (bar baz blah)
  (define (dskf)
    (void)))
```

Into this:

```scheme
(class* foo
        (bar baz blah)
        (define (dskf)
          (void)))
```

`class` seems to be handled better, oddly.

**Comment by sorawee** [comment]
This is another one I would encourage a PR from you, since it should be very straightforward :)
