### ISSUE TITLE
How to make Typed Racket look good?

### ISSUE THREAD

**Issue by pavpanchekha** [sorawee/fmt#79]
I just tried using this on some Typed Racket code and the proposed formatting looks a bit weird:

```
    (define best-alt-idxs
      :
      (Vectorof Integer)
      (make-vector number-of-points -1))
```

Now, maybe that's because I have a Typed Racket submodule inside some Racket code, and that's not handled well. Mea culpa if so. But is Typed Racket supported in general?

**Comment by jackfirth** [comment]
How does it look if you use the standalone version of `:` instead of `define:`?

```scheme
(: best-alt-idxs (Vectorof Integer))
(define best-alt-idxs (make-vector number-of-points -1))
```

**Comment by pavpanchekha** [comment]
Ah, then it looks much better and is entirely reasonable.
